# Step 1: Use base Python image
FROM python:3.9-slim

# Step 2: Set working directory
WORKDIR /app

# Step 3: Copy requirement files
COPY requirements.txt .

# Step 4: Install required packages
RUN pip install --no-cache-dir -r requirements.txt

# Step 5: Copy app folder and script
COPY app/ ./app/

# Step 6: Set default command to run script
CMD ["python", "./app/ingest.py"]
